export type Category = { url_part: string; type?: string, common_name: string };

export const CraigslistCategories: Category[] = [
  { url_part: "ccc", type: "main", common_name: "all-community" },
  { url_part: "act", common_name: "activities" },
  { url_part: "ats", common_name: "artists" },
  { url_part: "kid", common_name: "childcare" },
  { url_part: "cls", common_name: "classes" },
  { url_part: "eve", common_name: "events" },
  { url_part: "com", common_name: "general" },
  { url_part: "grp", common_name: "groups" },
  { url_part: "vnn", common_name: "local news" },
  { url_part: "laf", common_name: "lost found" },
  { url_part: "mis", common_name: "missed connections" },
  { url_part: "muc", common_name: "musicians" },
  { url_part: "pet", common_name: "pets" },
  { url_part: "pol", common_name: "politics" },
  { url_part: "rnr", common_name: "rants raves" },
  { url_part: "rid", common_name: "rideshare" },
  { url_part: "vol", common_name: "volunteers" },
  { url_part: "bbb", type: "main", common_name: "all-services" },
  { url_part: "aos", common_name: "automotive" },
  { url_part: "bts", common_name: "beauty" },
  { url_part: "cms", common_name: "cell/mobile" },
  { url_part: "cps", common_name: "computer" },
  { url_part: "crs", common_name: "creative" },
  { url_part: "cys", common_name: "cycle" },
  { url_part: "evs", common_name: "event" },
  { url_part: "fgs", common_name: "farm+garden" },
  { url_part: "fns", common_name: "financial" },
  { url_part: "hws", common_name: "health/well" },
  { url_part: "hss", common_name: "household" },
  { url_part: "lbs", common_name: "labor/move" },
  { url_part: "lgs", common_name: "legal" },
  { url_part: "lss", common_name: "lessons" },
  { url_part: "mas", common_name: "marine" },
  { url_part: "pas", common_name: "pet" },
  { url_part: "rts", common_name: "real estate" },
  { url_part: "sks", common_name: "skilled trade" },
  { url_part: "biz", common_name: "sm biz ads" },
  { url_part: "trv", common_name: "travel/vac" },
  { url_part: "wet", common_name: "write/ed/tran" },
  { url_part: "hhh", type: "main", common_name: "all-housing" },
  { url_part: "apa", common_name: "apts / housing" },
  { url_part: "swp", common_name: "housing swap" },
  { url_part: "hsw", common_name: "housing wanted" },
  { url_part: "off", common_name: "office / commercial" },
  { url_part: "prk", common_name: "parking / storage" },
  { url_part: "rea", common_name: "real estate for sale" },
  { url_part: "roo", common_name: "rooms / shared" },
  { url_part: "sha", common_name: "rooms wanted" },
  { url_part: "sub", common_name: "sublets / temporary" },
  { url_part: "vac", common_name: "vacation rentals" },
  { url_part: "sss", type: "main", common_name: "all-for sale" },
  { url_part: "ata", common_name: "antiques" },
  { url_part: "ppa", common_name: "appliances" },
  { url_part: "ara", common_name: "arts+crafts" },
  { url_part: "sna", common_name: "atv/utv/sno" },
  { url_part: "pta", common_name: "auto parts" },
  { url_part: "ava", common_name: "aviation" },
  { url_part: "baa", common_name: "baby+kid" },
  { url_part: "bar", common_name: "barter" },
  { url_part: "haa", common_name: "beauty+hlth" },
  { url_part: "bip", common_name: "bike parts" },
  { url_part: "bia", common_name: "bikes" },
  { url_part: "bpa", common_name: "boat parts" },
  { url_part: "boo", common_name: "boats" },
  { url_part: "bka", common_name: "books" },
  { url_part: "bfa", common_name: "business" },
  { url_part: "cta", common_name: "cars+trucks" },
  { url_part: "ema", common_name: "cds/dvd/vhs" },
  { url_part: "moa", common_name: "cell phones" },
  { url_part: "cla", common_name: "clothes+acc" },
  { url_part: "cba", common_name: "collectibles" },
  { url_part: "syp", common_name: "computer parts" },
  { url_part: "sya", common_name: "computers" },
  { url_part: "ela", common_name: "electronics" },
  { url_part: "gra", common_name: "farm+garden" },
  { url_part: "zip", common_name: "free" },
  { url_part: "fua", common_name: "furniture" },
  { url_part: "gms", common_name: "garage sale" },
  { url_part: "foa", common_name: "general" },
  { url_part: "hva", common_name: "heavy equip" },
  { url_part: "hsa", common_name: "household" },
  { url_part: "jwa", common_name: "jewelry" },
  { url_part: "maa", common_name: "materials" },
  { url_part: "mpa", common_name: "motorcycle parts" },
  { url_part: "mca", common_name: "motorcycles" },
  { url_part: "msa", common_name: "music instr" },
  { url_part: "pha", common_name: "photo+video" },
  { url_part: "rva", common_name: "rvs+camp" },
  { url_part: "sga", common_name: "sporting" },
  { url_part: "tia", common_name: "tickets" },
  { url_part: "tla", common_name: "tools" },
  { url_part: "taa", common_name: "toys+games" },
  { url_part: "tra", common_name: "trailers" },
  { url_part: "vga", common_name: "video gaming" },
  { url_part: "waa", common_name: "wanted" },
  { url_part: "wta", common_name: "wheels+tires" },
  { url_part: "jjj", type: "main", common_name: "all-jobs" },
  { url_part: "acc", common_name: "accounting+finance" },
  { url_part: "ofc", common_name: "admin / office" },
  { url_part: "egr", common_name: "arch / engineering" },
  { url_part: "med", common_name: "art / media / design" },
  { url_part: "sci", common_name: "biotech / science" },
  { url_part: "bus", common_name: "business / mgmt" },
  { url_part: "csr", common_name: "customer service" },
  { url_part: "edu", common_name: "education" },
  { url_part: "etc", common_name: "etc / misc" },
  { url_part: "fbh", common_name: "food / bev / hosp" },
  { url_part: "lab", common_name: "general labor" },
  { url_part: "gov", common_name: "government" },
  { url_part: "hum", common_name: "human resources" },
  { url_part: "lgl", common_name: "legal  /  paralegal" },
  { url_part: "mnu", common_name: "manufacturing" },
  { url_part: "mar", common_name: "marketing / pr / ad" },
  { url_part: "hea", common_name: "medical / health" },
  { url_part: "npo", common_name: "nonprofit sector" },
  { url_part: "rej", common_name: "real estate" },
  { url_part: "ret", common_name: "retail / wholesale" },
  { url_part: "sls", common_name: "sales / biz dev" },
  { url_part: "spa", common_name: "salon / spa / fitness" },
  { url_part: "sec", common_name: "security" },
  { url_part: "trd", common_name: "skilled trade / craft" },
  { url_part: "sof", common_name: "software / qa / dba" },
  { url_part: "sad", common_name: "systems / network" },
  { url_part: "tch", common_name: "technical support" },
  { url_part: "trp", common_name: "transport" },
  { url_part: "tfr", common_name: "tv / film / video" },
  { url_part: "web", common_name: "web / info design" },
  { url_part: "wri", common_name: "writing / editing" },
  { url_part: "ggg", type: "main", common_name: "all-gigs" },
  { url_part: "cpg", common_name: "computer" },
  { url_part: "crg", common_name: "creative" },
  { url_part: "cwg", common_name: "crew" },
  { url_part: "dmg", common_name: "domestic" },
  { url_part: "evg", common_name: "event" },
  { url_part: "lbg", common_name: "labor" },
  { url_part: "tlg", common_name: "talent" },
  { url_part: "wrg", common_name: "writing" },
  { url_part: "rrr", common_name: "resumes" },
];
