export type Location = { url_part: string; common_name: string };

export const CraigslistLocations: Location[] = [
  { url_part: "auburn", common_name: "auburn" },
  { url_part: "bham", common_name: "birmingham" },
  { url_part: "dothan", common_name: "dothan" },
  { url_part: "shoals", common_name: "florence  muscle shoals" },
  { url_part: "gadsden", common_name: "gadsden-anniston" },
  { url_part: "huntsville", common_name: "huntsville  decatur" },
  { url_part: "montgomery", common_name: "montgomery" },
  { url_part: "tuscaloosa", common_name: "tuscaloosa" },
  { url_part: "anchorage", common_name: "anchorage  mat-su" },
  { url_part: "fairbanks", common_name: "fairbanks" },
  { url_part: "kenai", common_name: "kenai peninsula" },
  { url_part: "juneau", common_name: "southeast alaska" },
  { url_part: "flagstaff", common_name: "flagstaff  sedona" },
  { url_part: "mohave", common_name: "mohave county" },
  { url_part: "phoenix", common_name: "phoenix" },
  { url_part: "prescott", common_name: "prescott" },
  { url_part: "showlow", common_name: "show low" },
  { url_part: "sierravista", common_name: "sierra vista" },
  { url_part: "tucson", common_name: "tucson" },
  { url_part: "yuma", common_name: "yuma" },
  { url_part: "fayar", common_name: "fayetteville " },
  { url_part: "fortsmith", common_name: "fort smith" },
  { url_part: "jonesboro", common_name: "jonesboro" },
  { url_part: "littlerock", common_name: "little rock" },
  { url_part: "texarkana", common_name: "texarkana" },
  { url_part: "bakersfield", common_name: "bakersfield" },
  { url_part: "chico", common_name: "chico" },
  { url_part: "fresno", common_name: "fresno  madera" },
  { url_part: "goldcountry", common_name: "gold country" },
  { url_part: "hanford", common_name: "hanford-corcoran" },
  { url_part: "humboldt", common_name: "humboldt county" },
  { url_part: "imperial", common_name: "imperial county" },
  { url_part: "inlandempire", common_name: "inland empire" },
  { url_part: "losangeles", common_name: "los angeles" },
  { url_part: "mendocino", common_name: "mendocino county" },
  { url_part: "merced", common_name: "merced" },
  { url_part: "modesto", common_name: "modesto" },
  { url_part: "monterey", common_name: "monterey bay" },
  { url_part: "orangecounty", common_name: "orange county" },
  { url_part: "palmsprings", common_name: "palm springs" },
  { url_part: "redding", common_name: "redding" },
  { url_part: "sacramento", common_name: "sacramento" },
  { url_part: "sandiego", common_name: "san diego" },
  { url_part: "sfbay", common_name: "san francisco bay area" },
  { url_part: "slo", common_name: "san luis obispo" },
  { url_part: "santabarbara", common_name: "santa barbara" },
  { url_part: "santamaria", common_name: "santa maria" },
  { url_part: "siskiyou", common_name: "siskiyou county" },
  { url_part: "stockton", common_name: "stockton" },
  { url_part: "susanville", common_name: "susanville" },
  { url_part: "ventura", common_name: "ventura county" },
  { url_part: "visalia", common_name: "visalia-tulare" },
  { url_part: "yubasutter", common_name: "yuba-sutter" },
  { url_part: "boulder", common_name: "boulder" },
  { url_part: "cosprings", common_name: "colorado springs" },
  { url_part: "denver", common_name: "denver" },
  { url_part: "eastco", common_name: "eastern CO" },
  { url_part: "fortcollins", common_name: "fort collins  north CO" },
  { url_part: "rockies", common_name: "high rockies" },
  { url_part: "pueblo", common_name: "pueblo" },
  { url_part: "westslope", common_name: "western slope" },
  { url_part: "newlondon", common_name: "eastern CT" },
  { url_part: "hartford", common_name: "hartford" },
  { url_part: "newhaven", common_name: "new haven" },
  { url_part: "nwct", common_name: "northwest CT" },
  { url_part: "delaware", common_name: "delaware" },
  { url_part: "washingtondc", common_name: "washington" },
  { url_part: "daytona", common_name: "daytona beach" },
  { url_part: "keys", common_name: "florida keys" },
  { url_part: "fortmyers", common_name: "ft myers  SW florida" },
  { url_part: "gainesville", common_name: "gainesville" },
  { url_part: "cfl", common_name: "heartland florida" },
  { url_part: "jacksonville", common_name: "jacksonville" },
  { url_part: "lakeland", common_name: "lakeland" },
  { url_part: "miami", common_name: "miami  dade" },
  { url_part: "lakecity", common_name: "north central FL" },
  { url_part: "ocala", common_name: "ocala" },
  { url_part: "okaloosa", common_name: "okaloosa  walton" },
  { url_part: "orlando", common_name: "orlando" },
  { url_part: "panamacity", common_name: "panama city" },
  { url_part: "pensacola", common_name: "pensacola" },
  { url_part: "sarasota", common_name: "sarasota-bradenton" },
  { url_part: "spacecoast", common_name: "space coast" },
  { url_part: "staugustine", common_name: "st augustine" },
  { url_part: "tallahassee", common_name: "tallahassee" },
  { url_part: "tampa", common_name: "tampa bay area" },
  { url_part: "treasure", common_name: "treasure coast" },
  { url_part: "albanyga", common_name: "albany " },
  { url_part: "athensga", common_name: "athens" },
  { url_part: "atlanta", common_name: "atlanta" },
  { url_part: "augusta", common_name: "augusta" },
  { url_part: "brunswick", common_name: "brunswick" },
  { url_part: "columbusga", common_name: "columbus " },
  { url_part: "macon", common_name: "macon  warner robins" },
  { url_part: "nwga", common_name: "northwest GA" },
  { url_part: "savannah", common_name: "savannah  hinesville" },
  { url_part: "statesboro", common_name: "statesboro" },
  { url_part: "valdosta", common_name: "valdosta" },
  { url_part: "honolulu", common_name: "hawaii" },
  { url_part: "boise", common_name: "boise" },
  { url_part: "eastidaho", common_name: "east idaho" },
  { url_part: "lewiston", common_name: "lewiston  clarkston" },
  { url_part: "twinfalls", common_name: "twin falls" },
  { url_part: "bn", common_name: "bloomington-normal" },
  { url_part: "chambana", common_name: "champaign urbana" },
  { url_part: "chicago", common_name: "chicago" },
  { url_part: "decatur", common_name: "decatur" },
  { url_part: "lasalle", common_name: "la salle co" },
  { url_part: "mattoon", common_name: "mattoon-charleston" },
  { url_part: "peoria", common_name: "peoria" },
  { url_part: "rockford", common_name: "rockford" },
  { url_part: "carbondale", common_name: "southern illinois" },
  { url_part: "springfieldil", common_name: "springfield " },
  { url_part: "quincy", common_name: "western IL" },
  { url_part: "bloomington", common_name: "bloomington" },
  { url_part: "evansville", common_name: "evansville" },
  { url_part: "fortwayne", common_name: "fort wayne" },
  { url_part: "indianapolis", common_name: "indianapolis" },
  { url_part: "kokomo", common_name: "kokomo" },
  { url_part: "tippecanoe", common_name: "lafayette  west lafayette" },
  { url_part: "muncie", common_name: "muncie  anderson" },
  { url_part: "richmondin", common_name: "richmond " },
  { url_part: "southbend", common_name: "south bend  michiana" },
  { url_part: "terrehaute", common_name: "terre haute" },
  { url_part: "ames", common_name: "ames" },
  { url_part: "cedarrapids", common_name: "cedar rapids" },
  { url_part: "desmoines", common_name: "des moines" },
  { url_part: "dubuque", common_name: "dubuque" },
  { url_part: "fortdodge", common_name: "fort dodge" },
  { url_part: "iowacity", common_name: "iowa city" },
  { url_part: "masoncity", common_name: "mason city" },
  { url_part: "quadcities", common_name: "quad cities" },
  { url_part: "siouxcity", common_name: "sioux city" },
  { url_part: "ottumwa", common_name: "southeast IA" },
  { url_part: "waterloo", common_name: "waterloo  cedar falls" },
  { url_part: "lawrence", common_name: "lawrence" },
  { url_part: "ksu", common_name: "manhattan" },
  { url_part: "nwks", common_name: "northwest KS" },
  { url_part: "salina", common_name: "salina" },
  { url_part: "seks", common_name: "southeast KS" },
  { url_part: "swks", common_name: "southwest KS" },
  { url_part: "topeka", common_name: "topeka" },
  { url_part: "wichita", common_name: "wichita" },
  { url_part: "bgky", common_name: "bowling green" },
  { url_part: "eastky", common_name: "eastern kentucky" },
  { url_part: "lexington", common_name: "lexington" },
  { url_part: "louisville", common_name: "louisville" },
  { url_part: "owensboro", common_name: "owensboro" },
  { url_part: "westky", common_name: "western KY" },
  { url_part: "batonrouge", common_name: "baton rouge" },
  { url_part: "cenla", common_name: "central louisiana" },
  { url_part: "houma", common_name: "houma" },
  { url_part: "lafayette", common_name: "lafayette" },
  { url_part: "lakecharles", common_name: "lake charles" },
  { url_part: "monroe", common_name: "monroe" },
  { url_part: "neworleans", common_name: "new orleans" },
  { url_part: "shreveport", common_name: "shreveport" },
  { url_part: "maine", common_name: "maine" },
  { url_part: "annapolis", common_name: "annapolis" },
  { url_part: "baltimore", common_name: "baltimore" },
  { url_part: "easternshore", common_name: "eastern shore" },
  { url_part: "frederick", common_name: "frederick" },
  { url_part: "smd", common_name: "southern maryland" },
  { url_part: "westmd", common_name: "western maryland" },
  { url_part: "boston", common_name: "boston" },
  { url_part: "capecod", common_name: "cape cod  islands" },
  { url_part: "southcoast", common_name: "south coast" },
  { url_part: "westernmass", common_name: "western massachusetts" },
  { url_part: "worcester", common_name: "worcester  central MA" },
  { url_part: "annarbor", common_name: "ann arbor" },
  { url_part: "battlecreek", common_name: "battle creek" },
  { url_part: "centralmich", common_name: "central michigan" },
  { url_part: "detroit", common_name: "detroit metro" },
  { url_part: "flint", common_name: "flint" },
  { url_part: "grandrapids", common_name: "grand rapids" },
  { url_part: "holland", common_name: "holland" },
  { url_part: "jxn", common_name: "jackson " },
  { url_part: "kalamazoo", common_name: "kalamazoo" },
  { url_part: "lansing", common_name: "lansing" },
  { url_part: "monroemi", common_name: "monroe " },
  { url_part: "muskegon", common_name: "muskegon" },
  { url_part: "nmi", common_name: "northern michigan" },
  { url_part: "porthuron", common_name: "port huron" },
  { url_part: "saginaw", common_name: "saginaw-midland-baycity" },
  { url_part: "swmi", common_name: "southwest michigan" },
  { url_part: "thumb", common_name: "the thumb" },
  { url_part: "up", common_name: "upper peninsula" },
  { url_part: "bemidji", common_name: "bemidji" },
  { url_part: "brainerd", common_name: "brainerd" },
  { url_part: "duluth", common_name: "duluth  superior" },
  { url_part: "mankato", common_name: "mankato" },
  { url_part: "minneapolis", common_name: "minneapolis  st paul" },
  { url_part: "rmn", common_name: "rochester " },
  { url_part: "marshall", common_name: "southwest MN" },
  { url_part: "stcloud", common_name: "st cloud" },
  { url_part: "gulfport", common_name: "gulfport  biloxi" },
  { url_part: "hattiesburg", common_name: "hattiesburg" },
  { url_part: "jackson", common_name: "jackson" },
  { url_part: "meridian", common_name: "meridian" },
  { url_part: "northmiss", common_name: "north mississippi" },
  { url_part: "natchez", common_name: "southwest MS" },
  { url_part: "columbiamo", common_name: "columbia  jeff city" },
  { url_part: "joplin", common_name: "joplin" },
  { url_part: "kansascity", common_name: "kansas city" },
  { url_part: "kirksville", common_name: "kirksville" },
  { url_part: "loz", common_name: "lake of the ozarks" },
  { url_part: "semo", common_name: "southeast missouri" },
  { url_part: "springfield", common_name: "springfield" },
  { url_part: "stjoseph", common_name: "st joseph" },
  { url_part: "stlouis", common_name: "st louis" },
  { url_part: "billings", common_name: "billings" },
  { url_part: "bozeman", common_name: "bozeman" },
  { url_part: "butte", common_name: "butte" },
  { url_part: "greatfalls", common_name: "great falls" },
  { url_part: "helena", common_name: "helena" },
  { url_part: "kalispell", common_name: "kalispell" },
  { url_part: "missoula", common_name: "missoula" },
  { url_part: "montana", common_name: "eastern montana" },
  { url_part: "grandisland", common_name: "grand island" },
  { url_part: "lincoln", common_name: "lincoln" },
  { url_part: "northplatte", common_name: "north platte" },
  { url_part: "omaha", common_name: "omaha  council bluffs" },
  { url_part: "scottsbluff", common_name: "scottsbluff  panhandle" },
  { url_part: "elko", common_name: "elko" },
  { url_part: "lasvegas", common_name: "las vegas" },
  { url_part: "reno", common_name: "reno  tahoe" },
  { url_part: "nh", common_name: "new hampshire" },
  { url_part: "cnj", common_name: "central NJ" },
  { url_part: "jerseyshore", common_name: "jersey shore" },
  { url_part: "newjersey", common_name: "north jersey" },
  { url_part: "southjersey", common_name: "south jersey" },
  { url_part: "albuquerque", common_name: "albuquerque" },
  { url_part: "clovis", common_name: "clovis  portales" },
  { url_part: "farmington", common_name: "farmington" },
  { url_part: "lascruces", common_name: "las cruces" },
  { url_part: "roswell", common_name: "roswell  carlsbad" },
  { url_part: "santafe", common_name: "santa fe  taos" },
  { url_part: "albany", common_name: "albany" },
  { url_part: "binghamton", common_name: "binghamton" },
  { url_part: "buffalo", common_name: "buffalo" },
  { url_part: "catskills", common_name: "catskills" },
  { url_part: "chautauqua", common_name: "chautauqua" },
  { url_part: "elmira", common_name: "elmira-corning" },
  { url_part: "fingerlakes", common_name: "finger lakes" },
  { url_part: "glensfalls", common_name: "glens falls" },
  { url_part: "hudsonvalley", common_name: "hudson valley" },
  { url_part: "ithaca", common_name: "ithaca" },
  { url_part: "longisland", common_name: "long island" },
  { url_part: "newyork", common_name: "new york city" },
  { url_part: "oneonta", common_name: "oneonta" },
  { url_part: "plattsburgh", common_name: "plattsburgh-adirondacks" },
  { url_part: "potsdam", common_name: "potsdam-canton-massena" },
  { url_part: "rochester", common_name: "rochester" },
  { url_part: "syracuse", common_name: "syracuse" },
  { url_part: "twintiers", common_name: "twin tiers NY/PA" },
  { url_part: "utica", common_name: "utica-rome-oneida" },
  { url_part: "watertown", common_name: "watertown" },
  { url_part: "asheville", common_name: "asheville" },
  { url_part: "boone", common_name: "boone" },
  { url_part: "charlotte", common_name: "charlotte" },
  { url_part: "eastnc", common_name: "eastern NC" },
  { url_part: "fayetteville", common_name: "fayetteville" },
  { url_part: "greensboro", common_name: "greensboro" },
  { url_part: "hickory", common_name: "hickory  lenoir" },
  { url_part: "onslow", common_name: "jacksonville " },
  { url_part: "outerbanks", common_name: "outer banks" },
  { url_part: "raleigh", common_name: "raleigh  durham  CH" },
  { url_part: "wilmington", common_name: "wilmington" },
  { url_part: "winstonsalem", common_name: "winston-salem" },
  { url_part: "bismarck", common_name: "bismarck" },
  { url_part: "fargo", common_name: "fargo  moorhead" },
  { url_part: "grandforks", common_name: "grand forks" },
  { url_part: "nd", common_name: "north dakota" },
  { url_part: "akroncanton", common_name: "akron  canton" },
  { url_part: "ashtabula", common_name: "ashtabula" },
  { url_part: "athensohio", common_name: "athens " },
  { url_part: "chillicothe", common_name: "chillicothe" },
  { url_part: "cincinnati", common_name: "cincinnati" },
  { url_part: "cleveland", common_name: "cleveland" },
  { url_part: "columbus", common_name: "columbus" },
  { url_part: "dayton", common_name: "dayton  springfield" },
  { url_part: "limaohio", common_name: "lima  findlay" },
  { url_part: "mansfield", common_name: "mansfield" },
  { url_part: "sandusky", common_name: "sandusky" },
  { url_part: "toledo", common_name: "toledo" },
  { url_part: "tuscarawas", common_name: "tuscarawas co" },
  { url_part: "youngstown", common_name: "youngstown" },
  { url_part: "zanesville", common_name: "zanesville  cambridge" },
  { url_part: "lawton", common_name: "lawton" },
  { url_part: "enid", common_name: "northwest OK" },
  { url_part: "oklahomacity", common_name: "oklahoma city" },
  { url_part: "stillwater", common_name: "stillwater" },
  { url_part: "tulsa", common_name: "tulsa" },
  { url_part: "bend", common_name: "bend" },
  { url_part: "corvallis", common_name: "corvallis/albany" },
  { url_part: "eastoregon", common_name: "east oregon" },
  { url_part: "eugene", common_name: "eugene" },
  { url_part: "klamath", common_name: "klamath falls" },
  { url_part: "medford", common_name: "medford-ashland" },
  { url_part: "oregoncoast", common_name: "oregon coast" },
  { url_part: "portland", common_name: "portland" },
  { url_part: "roseburg", common_name: "roseburg" },
  { url_part: "salem", common_name: "salem" },
  { url_part: "altoona", common_name: "altoona-johnstown" },
  { url_part: "chambersburg", common_name: "cumberland valley" },
  { url_part: "erie", common_name: "erie" },
  { url_part: "harrisburg", common_name: "harrisburg" },
  { url_part: "lancaster", common_name: "lancaster" },
  { url_part: "allentown", common_name: "lehigh valley" },
  { url_part: "meadville", common_name: "meadville" },
  { url_part: "philadelphia", common_name: "philadelphia" },
  { url_part: "pittsburgh", common_name: "pittsburgh" },
  { url_part: "poconos", common_name: "poconos" },
  { url_part: "reading", common_name: "reading" },
  { url_part: "scranton", common_name: "scranton  wilkes-barre" },
  { url_part: "pennstate", common_name: "state college" },
  { url_part: "williamsport", common_name: "williamsport" },
  { url_part: "york", common_name: "york" },
  { url_part: "providence", common_name: "rhode island" },
  { url_part: "charleston", common_name: "charleston" },
  { url_part: "columbia", common_name: "columbia" },
  { url_part: "florencesc", common_name: "florence" },
  { url_part: "greenville", common_name: "greenville  upstate" },
  { url_part: "hiltonhead", common_name: "hilton head" },
  { url_part: "myrtlebeach", common_name: "myrtle beach" },
  { url_part: "nesd", common_name: "northeast SD" },
  { url_part: "csd", common_name: "pierre  central SD" },
  { url_part: "rapidcity", common_name: "rapid city  west SD" },
  { url_part: "siouxfalls", common_name: "sioux falls  SE SD" },
  { url_part: "sd", common_name: "south dakota" },
  { url_part: "chattanooga", common_name: "chattanooga" },
  { url_part: "clarksville", common_name: "clarksville" },
  { url_part: "cookeville", common_name: "cookeville" },
  { url_part: "jacksontn", common_name: "jackson  " },
  { url_part: "knoxville", common_name: "knoxville" },
  { url_part: "memphis", common_name: "memphis" },
  { url_part: "nashville", common_name: "nashville" },
  { url_part: "tricities", common_name: "tri-cities" },
  { url_part: "abilene", common_name: "abilene" },
  { url_part: "amarillo", common_name: "amarillo" },
  { url_part: "austin", common_name: "austin" },
  { url_part: "beaumont", common_name: "beaumont  port arthur" },
  { url_part: "brownsville", common_name: "brownsville" },
  { url_part: "collegestation", common_name: "college station" },
  { url_part: "corpuschristi", common_name: "corpus christi" },
  { url_part: "dallas", common_name: "dallas  fort worth" },
  { url_part: "nacogdoches", common_name: "deep east texas" },
  { url_part: "delrio", common_name: "del rio  eagle pass" },
  { url_part: "elpaso", common_name: "el paso" },
  { url_part: "galveston", common_name: "galveston" },
  { url_part: "houston", common_name: "houston" },
  { url_part: "killeen", common_name: "killeen  temple  ft hood" },
  { url_part: "laredo", common_name: "laredo" },
  { url_part: "lubbock", common_name: "lubbock" },
  { url_part: "mcallen", common_name: "mcallen  edinburg" },
  { url_part: "odessa", common_name: "odessa  midland" },
  { url_part: "sanangelo", common_name: "san angelo" },
  { url_part: "sanantonio", common_name: "san antonio" },
  { url_part: "sanmarcos", common_name: "san marcos" },
  { url_part: "bigbend", common_name: "southwest TX" },
  { url_part: "texoma", common_name: "texoma" },
  { url_part: "easttexas", common_name: "tyler  east TX" },
  { url_part: "victoriatx", common_name: "victoria " },
  { url_part: "waco", common_name: "waco" },
  { url_part: "wichitafalls", common_name: "wichita falls" },
  { url_part: "logan", common_name: "logan" },
  { url_part: "ogden", common_name: "ogden-clearfield" },
  { url_part: "provo", common_name: "provo  orem" },
  { url_part: "saltlakecity", common_name: "salt lake city" },
  { url_part: "stgeorge", common_name: "st george" },
  { url_part: "vermont", common_name: "vermont" },
  { url_part: "charlottesville", common_name: "charlottesville" },
  { url_part: "danville", common_name: "danville" },
  { url_part: "fredericksburg", common_name: "fredericksburg" },
  { url_part: "norfolk", common_name: "hampton roads" },
  { url_part: "harrisonburg", common_name: "harrisonburg" },
  { url_part: "lynchburg", common_name: "lynchburg" },
  { url_part: "blacksburg", common_name: "new river valley" },
  { url_part: "richmond", common_name: "richmond" },
  { url_part: "roanoke", common_name: "roanoke" },
  { url_part: "swva", common_name: "southwest VA" },
  { url_part: "winchester", common_name: "winchester" },
  { url_part: "bellingham", common_name: "bellingham" },
  { url_part: "kpr", common_name: "kennewick-pasco-richland" },
  { url_part: "moseslake", common_name: "moses lake" },
  { url_part: "olympic", common_name: "olympic peninsula" },
  { url_part: "pullman", common_name: "pullman  moscow" },
  { url_part: "seattle", common_name: "seattle-tacoma" },
  { url_part: "skagit", common_name: "skagit  island  SJI" },
  { url_part: "spokane", common_name: "spokane  coeur d'alene" },
  { url_part: "wenatchee", common_name: "wenatchee" },
  { url_part: "yakima", common_name: "yakima" },
  { url_part: "charlestonwv", common_name: "charleston " },
  { url_part: "martinsburg", common_name: "eastern panhandle" },
  { url_part: "huntington", common_name: "huntington-ashland" },
  { url_part: "morgantown", common_name: "morgantown" },
  { url_part: "wheeling", common_name: "northern panhandle" },
  { url_part: "parkersburg", common_name: "parkersburg-marietta" },
  { url_part: "swv", common_name: "southern WV" },
  { url_part: "wv", common_name: "west virginia (old)" },
  { url_part: "appleton", common_name: "appleton-oshkosh-FDL" },
  { url_part: "eauclaire", common_name: "eau claire" },
  { url_part: "greenbay", common_name: "green bay" },
  { url_part: "janesville", common_name: "janesville" },
  { url_part: "racine", common_name: "kenosha-racine" },
  { url_part: "lacrosse", common_name: "la crosse" },
  { url_part: "madison", common_name: "madison" },
  { url_part: "milwaukee", common_name: "milwaukee" },
  { url_part: "northernwi", common_name: "northern WI" },
  { url_part: "sheboygan", common_name: "sheboygan" },
  { url_part: "wausau", common_name: "wausau" },
  { url_part: "wyoming", common_name: "wyoming" },
];
